apiVersion: v1
kind: Service
metadata:
  name: {{ include "mp-eth-node.fullname" . }}
  labels:
    {{- include "mp-eth-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ required "A valid .Values.global.mpETHNodePort entry required!" .Values.global.mpETHNodePort }}
      targetPort: {{ required "A valid .Values.global.mpETHNodePort entry required!" .Values.global.mpETHNodePort }}
      protocol: TCP
      name: {{ required "A valid .Values.global.mpETHNodePortName entry required!" .Values.global.mpETHNodePortName }}
    - port: {{ required "A valid .Values.global.mpETHNodeRPCPort entry required!" .Values.global.mpETHNodeRPCPort }}
      targetPort: {{ required "A valid .Values.global.mpETHNodeRPCPort entry required!" .Values.global.mpETHNodeRPCPort }}
      protocol: TCP
      name: {{ required "A valid .Values.global.mpETHNodeRPCPortName entry required!" .Values.global.mpETHNodeRPCPortName }}
  selector:
  {{- include "mp-eth-node.selectorLabels" . | nindent 4 }}
